[project]
name = "test1"
version = "0.1.0"
description = "Core logic, configuration and utilities for the project"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.0.0",
    "structlog>=24.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/test1"]
