name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:

  tests:
    runs-on: ubuntu-latest
    container: python:3.13

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Dependencies
        run: uv sync --dev

      - name: Run Tests
        run: uv run pytest -v -p no:warnings --junitxml=report.xml tests/

      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: report.xml
          retention-days: 10

  pages:
    runs-on: ubuntu-latest
    container: python:3.13

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Dependencies
        run: uv sync --dev

      - name: Build docs
        run: uv run mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
