name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish Release for test1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: |
          uv run pytest packages/*/tests --cov=packages --cov-report=xml --cov-report=html || \
          if [ $? -eq 5 ]; then echo "No tests found - skipping."; exit 0; 
          else echo "Tests failed."; exit 1; fi

      - name: Build package
        run: |
          for dir in packages/*/; do
            echo "Building $dir"
            uv build "$dir" --out-dir dist
          done

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          
          password: ${{ secrets.PYPI_API_TOKEN }}
          

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
          
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          